when:
    - event: push
      branch: main

clone:
  - name: git
    image: woodpeckerci/plugin-git
    settings:
      tags: true

steps:
  - name: debug
    image: alpine
    commands:
      - pwd
      - ls -al
      - ls -al /app
      - cat /app/opengsync.yaml
      - cat /app/compose.override.yaml

  - name: deploy
    image: docker:27-cli
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      OPENGSYNC_PORT:
        from_secret: OPENGSYNC_PORT
      OPENGSYNC_SERVER_NAME:
        from_secret: OPENGSYNC_SERVER_NAME
      POSTGRES_USER:
        from_secret: POSTGRES_USER
      POSTGRES_PASSWORD:
        from_secret: POSTGRES_PASSWORD
      POSTGRES_DB:
        from_secret: POSTGRES_DB
      POSTGRES_PORT:
        from_secret: POSTGRES_PORT
      POSTGRES_HOST:
        from_secret: POSTGRES_HOST
      SECRET_KEY:
        from_secret: SECRET_KEY
      PGADMIN_EMAIL:
        from_secret: PGADMIN_EMAIL
      PGADMIN_PASSWORD:
        from_secret: PGADMIN_PASSWORD
      PGADMIN_PORT:
        from_secret: PGADMIN_PORT
      POSTGRES_REPLICATOR_PASSWORD:
        from_secret: POSTGRES_REPLICATOR_PASSWORD
      MAIL_SERVER:
        from_secret: MAIL_SERVER
      MAIL_USER:
        from_secret: MAIL_USER
      MAIL_SENDER:
        from_secret: MAIL_SENDER
      MAIL_PASSWORD:
        from_secret: MAIL_PASSWORD
      MAIL_PORT:
        from_secret: MAIL_PORT
      GEMINI_API_KEY:
        from_secret: GEMINI_API_KEY
      TIMEZONE:
        from_secret: TIMEZONE
      REDIS_PORT:
        from_secret: REDIS_PORT
      ILLUMINA_RUN_FOLDER:
        from_secret: ILLUMINA_RUN_FOLDER
      MEDIA_DIR:
        from_secret: MEDIA_DIR
      LOG_DIR:
        from_secret: LOG_DIR
      UPLOADS_DIR:
        from_secret: UPLOADS_DIR
      DB_DIR:
        from_secret: DB_DIR
      PUID:
        from_secret: PUID
      PGID:
        from_secret: PGID
      OPENGSYNC_CONFIG_FILE:
        from_secret: OPENGSYNC_CONFIG_FILE
    commands:
      - git describe --tags
      - docker compose -f compose.yaml -f /app/compose.override.yaml -p opengsync-prod build --build-arg "VERSION=$(git describe --tags --abbrev=0)"
      - docker compose -f compose.yaml -f /app/compose.override.yaml -p opengsync-prod up -d --remove-orphans --wait
      - docker image prune -f

