services:
    opengsync-app:
        container_name: opengsync-app-dev
        build:
            context: .
            dockerfile: ./services/Dockerfile.dev
            target: opengsync-app
        volumes:
            - ./packages/opengsync-server:/app/packages/opengsync-server
            - ./packages/opengsync-db:/app/packages/opengsync-db
            - ./opengsync.yaml:/app/opengsync.yaml:ro
            - ./services/opengsync-app/static/images:/static/images:ro
            - ./services/opengsync-app/static/js:/static/js:ro
            - ./services/opengsync-app/static/resources:/static/resources:ro
            - ./services/opengsync-app/templates:/templates:ro
            - ${UPLOADS_DIR}:/uploads
            - ${DATA_DIR}/media:/media
            - ${DATA_DIR}/logs/opengsync:/logs
            - ./share:/share:ro
            - compiled_css:/static/style/compiled:ro
        environment:
            TZ: ${TIMEZONE}
            OPENGSYNC_PORT: ${OPENGSYNC_PORT}
            REDIS_PORT: ${REDIS_PORT}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_HOST: ${POSTGRES_HOST}
            POSTGRES_PORT: ${POSTGRES_PORT}
            MAIL_SERVER: ${MAIL_SERVER}
            MAIL_PORT: ${MAIL_PORT}
            MAIL_SENDER: ${MAIL_SENDER}
            MAIL_PASSWORD: ${MAIL_PASSWORD}
            SECRET_KEY: ${SECRET_KEY}
            MAIL_USER: ${MAIL_USER}
            OPENGSYNC_DEBUG: 1
        ports:
            - ${OPENGSYNC_PORT}:${OPENGSYNC_PORT}
        expose:
            - ${OPENGSYNC_PORT}
        restart: always
        depends_on:
            postgres:
                condition: service_healthy
                restart: true
            sass-compiler:
                condition: service_started
                restart: true
            redis-cache:
                condition: service_healthy
                restart: true
        healthcheck:
            test: ["CMD", "curl", "-f", "http://opengsync-app:${OPENGSYNC_PORT}/status/"]
            interval: 10s
            timeout: 10s

    opengsync-celery-worker:
        container_name: opengsync-celery-worker-dev
        build:
            context: .
            dockerfile: ./services/Dockerfile.dev
            target: celery-worker
        environment:
            TZ: ${TIMEZONE}
            REDIS_PORT: ${REDIS_PORT}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_HOST: ${POSTGRES_HOST}
            POSTGRES_PORT: ${POSTGRES_PORT}
        volumes:
            - ./opengsync.yaml:/app/opengsync.yaml:ro
            - ${ILLUMINA_RUN_FOLDER}:/illumina_run_folder
            - ${DATA_DIR}/logs/celery-worker:/logs
            - ${UPLOADS_DIR}:/uploads
        depends_on:
            opengsync-celery-beat:
                condition: service_started
                restart: true
            postgres:
                condition: service_healthy
                restart: true
        restart: always
        command: >
            celery -A opengsync_worker.celery worker --loglevel=info

    opengsync-celery-beat:
        container_name: opengsync-celery-beat-dev
        build:
            context: .
            dockerfile: ./services/Dockerfile.dev
            target: celery-worker
        environment:
            TZ: ${TIMEZONE}
            REDIS_PORT: ${REDIS_PORT}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_HOST: ${POSTGRES_HOST}
            POSTGRES_PORT: ${POSTGRES_PORT}
        volumes:
            - ./opengsync.yaml:/app/opengsync.yaml:ro
        depends_on:
            postgres:
                condition: service_healthy
                restart: true
            redis-cache:
                condition: service_healthy
                restart: true
        restart: unless-stopped
        command: >
            celery -A opengsync_worker.celery beat --loglevel=info

    redis-cache:
        container_name: redis-cache-dev
        image: redis:8.0.3-alpine3.21
        environment:
            TZ: ${TIMEZONE}
        ports:
            - ${REDIS_PORT}:${REDIS_PORT}
        restart: unless-stopped
        volumes:
            - ./cache:/data
        healthcheck:
            test: ["CMD", "redis-cli", "-p", "${REDIS_PORT}", "ping"]
            interval: 10s
            timeout: 10s
            retries: 5
        command: --port ${REDIS_PORT}

    sass-compiler:
        container_name: sass-compiler-dev
        build: ./services/sass-compiler
        volumes:
            - ./services/opengsync-app/static/style/sass:/app/static/style/sass:ro
            - compiled_css:/app/static/style/compiled
        command: "sass --watch /app/static/style/sass:/app/static/style/compiled"
        environment:
            - TZ=${TIMEZONE}
        restart: unless-stopped
        healthcheck:
            test: ["CMD-SHELL", "ps cax | grep -wq sass"]
            interval: 10s
            timeout: 10s
            retries: 5

    postgres:
        container_name: postgres-dev
        image: postgres:17-alpine
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
            PGPORT: ${POSTGRES_PORT}
            TZ: ${TIMEZONE}
        expose:
            - ${POSTGRES_PORT}
        ports:
            - ${POSTGRES_PORT}:${POSTGRES_PORT}
        restart: unless-stopped
        volumes:
            - ./templates/postgres/postgresql.conf:/etc/postgresql.conf
            - ${DB_DIR}/postgres:/var/lib/postgresql/data
            - ${DB_DIR}/archive:/var/lib/postgresql/archive
        healthcheck:
            test: ["CMD", "pg_isready", "-d", "${POSTGRES_DB}", "-U", "${POSTGRES_USER}"]
            interval: 10s
            timeout: 10s
            retries: 5
        command: "postgres -c config_file=/etc/postgresql.conf"

    # pgadmin:
    #     container_name: pgadmin-dev
    #     image: dpage/pgadmin4:latest
    #     environment:
    #         PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
    #         PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    #         TZ: ${TIMEZONE}
    #     ports:
    #         - ${PGADMIN_PORT}:80
    #     restart: unless-stopped
    #     volumes:
    #         - ${DB_DIR}/pgadmin:/var/lib/pgadmin
    #     depends_on:
    #         postgres:
    #             condition: service_healthy
    #             restart: true
    #     attach: false  # no logs

volumes:
    compiled_css:
    yacht: