services:
    opengsync-pytest:
        container_name: opengsync-pytest
        build:
            context: .
            dockerfile: ./services/Dockerfile
            target: pytest
        command: "pytest tests/ --capture=tee-sys -vv -W always"
        environment:
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: password
            POSTGRES_DB: test_db
            POSTGRES_PORT: 5434
            POSTGRES_HOST: postgres
            TIMEZONE: "Europe/Vienna"
            TZ: "Europe/Vienna"
        depends_on:
            postgres:
                condition: service_healthy
                restart: true

    postgres:
        container_name: opengsync-postgres-db-test
        image: postgres:17-alpine
        command: "-c logging_collector=on"
        environment:
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: password
            POSTGRES_DB: test_db
            PGPORT: 5434
            TZ: "Europe/Vienna"
        expose:
            - 5434
        ports:
            - 5434:5434
        healthcheck:
            test: ["CMD", "pg_isready", "-d", "test_db", "-U", "admin"]
            interval: 10s
            timeout: 10s
            retries: 5