services:
    opengsync-app:
        platform: linux/amd64
        container_name: opengsync-app-dev
        build:
            context: ./services/opengsync-app
            dockerfile: Dockerfile.dev
        volumes:
            - ./services/opengsync-app/opengsync-server:/app/opengsync-server
            - ./services/opengsync-app/opengsync-db:/app/opengsync-db
            - ./opengsync.yaml:/app/opengsync.yaml:ro
            - ./services/opengsync-app/static/images:/static/images:ro
            - ./services/opengsync-app/static/js:/static/js:ro
            - ./services/opengsync-app/static/resources:/static/resources:ro
            - ./services/opengsync-app/templates:/templates:ro
            - ${UPLOADS_DIR}:/uploads
            - ${DATA_DIR}/media:/media
            - ${DATA_DIR}/logs/opengsync:/logs
            - ./share:/share:ro
            - compiled_css:/static/style/compiled:ro
        environment:
            TZ: ${TIMEZONE}
        env_file: .env
        ports:
            - ${OPENGSYNC_PORT}:${OPENGSYNC_PORT}
        expose:
            - ${OPENGSYNC_PORT}
        restart: always
        depends_on:
            postgres:
                condition: service_healthy
                restart: true
            sass-compiler:
                condition: service_started
                restart: true
            redis-cache:
                condition: service_healthy
                restart: true
        healthcheck:
            test: ["CMD", "curl", "-f", "http://opengsync-app:${OPENGSYNC_PORT}/status"]
            interval: 10s
            timeout: 10s
        command: "sh ./entrypoint.sh"

    celery-worker:
        platform: linux/amd64
        container_name: celery-worker-dev
        build:
            context: ./services
            dockerfile: celery/Dockerfile
        env_file: .env
        environment:
            TZ: ${TIMEZONE}
        volumes:
            - ./opengsync.yaml:/app/opengsync.yaml:ro
            - ${ILLUMINA_RUN_FOLDER}:/illumina_run_folder
            - ${DATA_DIR}/logs/celery-worker:/logs
            - ${UPLOADS_DIR}:/uploads
        depends_on:
            celery-scheduler:
                condition: service_started
                restart: true
            postgres:
                condition: service_healthy
                restart: true
        restart: always
        command: >
            celery -A scheduler.celery worker --loglevel=info

    celery-scheduler:
        platform: linux/amd64
        container_name: celery-scheduler-dev
        build:
            context: ./services
            dockerfile: celery/Dockerfile
        env_file: .env
        environment:
            TZ: ${TIMEZONE}
        volumes:
            - ./opengsync.yaml:/app/opengsync.yaml:ro
        depends_on:
            postgres:
                condition: service_healthy
                restart: true
            redis-cache:
                condition: service_healthy
                restart: true
        restart: always
        command: >
            celery -A scheduler.celery beat --loglevel=info

    celery-flower:
        platform: linux/amd64
        container_name: celery-flower-dev
        build:
            context: ./services
            dockerfile: celery/Dockerfile.flower
        environment:
            TZ: ${TIMEZONE}
        depends_on:
            redis-cache:
                condition: service_healthy
                restart: true
        ports:
            - 5555:5555
        restart: always
        command: >
            celery --broker=redis://redis-cache:${REDIS_PORT}/4 flower --port=5555 --basic-auth="${FLOWER_USER}:${FLOWER_PASSWORD}"

    redis-cache:
        container_name: redis-cache-dev
        image: redis:8.0.3-alpine3.21
        environment:
            - TZ=${TIMEZONE}
        ports:
            - ${REDIS_PORT}:${REDIS_PORT}
        restart: always
        volumes:
            - ./cache:/data
        healthcheck:
            test: ["CMD", "redis-cli", "-p", "${REDIS_PORT}", "ping"]
            interval: 10s
            timeout: 10s
            retries: 5
        command: --port ${REDIS_PORT}

    sass-compiler:
        container_name: sass-compiler-dev
        build: ./services/sass-compiler
        volumes:
            - ./services/opengsync-app/static/style/sass:/app/static/style/sass:ro
            - compiled_css:/app/static/style/compiled
        command: "sass --watch /app/static/style/sass:/app/static/style/compiled"
        environment:
            - TZ=${TIMEZONE}
        healthcheck:
            test: ["CMD-SHELL", "ps cax | grep -wq sass"]
            interval: 10s
            timeout: 10s
            retries: 5

    postgres:
        container_name: postgres-dev
        image: postgres:17-alpine
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
            PGPORT: ${POSTGRES_PORT}
            TZ: ${TIMEZONE}
        expose:
            - ${POSTGRES_PORT}
        ports:
            - ${POSTGRES_PORT}:${POSTGRES_PORT}
        restart: always
        volumes:
            - ./templates/postgres/postgresql.conf:/etc/postgresql.conf
            - ${DB_DIR}/postgres:/var/lib/postgresql/data
            - ${DB_DIR}/archive:/var/lib/postgresql/archive
        healthcheck:
            test: ["CMD", "pg_isready", "-d", "${POSTGRES_DB}", "-U", "${POSTGRES_USER}"]
            interval: 10s
            timeout: 10s
            retries: 5
        command: "postgres -c config_file=/etc/postgresql.conf"

    pgadmin:
        container_name: pgadmin-dev
        image: dpage/pgadmin4:latest
        environment:
            PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
            PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
            TZ: ${TIMEZONE}
        ports:
            - ${PGADMIN_PORT}:80
        restart: always
        volumes:
            - ${DB_DIR}/pgadmin:/var/lib/pgadmin
        depends_on:
            postgres:
                condition: service_healthy
                restart: true
        attach: false  # no logs

    # yacht:
    #     container_name: yacht-dev
    #     environment:
    #         TZ: ${TIMEZONE}
    #     image: selfhostedpro/yacht:latest
    #     ports:
    #         - ${YACHT_PORT}:8000
    #     volumes:
    #         - /var/run/docker.sock:/var/run/docker.sock
    #         - yacht:/config
    #     restart: always

volumes:
    compiled_css:
    yacht: