services:
    db-migrator:
        image: ghcr.io/lutrarutra/opengsync-app/migrator:${APP_VERSION:-latest}
        container_name: opengsync-db-migrator
        platform: linux/amd64
        environment:
            TZ: ${TIMEZONE}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_HOST: ${POSTGRES_HOST:-postgres}
            POSTGRES_PORT: ${POSTGRES_PORT}
        depends_on:
            postgres:
                condition: service_healthy
        restart: "no"

    opengsync-app:
        image: ghcr.io/lutrarutra/opengsync-app/backend:${APP_VERSION:-latest}
        platform: linux/amd64
        user: "${PUID:-1000}:${PGID:-1000}"
        container_name: opengsync-app
        restart: unless-stopped
        deploy:
            update_config:
                order: start-first
        volumes:
            - compiled_css:/static/style/compiled:ro
            - ${OPENGSYNC_CONFIG_FILE}:/app/opengsync.yaml:ro
            - ${UPLOADS_DIR}:/uploads
            - ${MEDIA_DIR}:/media
            - ${LOG_DIR}/opengsync:/logs
        environment:
            OPENGSYNC_PORT: ${OPENGSYNC_PORT}
            TZ: ${TIMEZONE}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_HOST: ${POSTGRES_HOST}
            POSTGRES_PORT: ${POSTGRES_PORT}
            MAIL_SERVER: ${MAIL_SERVER}
            MAIL_PORT: ${MAIL_PORT}
            MAIL_SENDER: ${MAIL_SENDER}
            MAIL_PASSWORD: ${MAIL_PASSWORD}
            SECRET_KEY: ${SECRET_KEY}
            MAIL_USER: ${MAIL_USER}
            ENVIRONMENT: prod
        expose:
            - "5000"
        depends_on:
            postgres:
                condition: service_healthy
                restart: true
            tailwind-compiler:
                condition: service_completed_successfully
            redis-cache:
                condition: service_healthy
                restart: true
        healthcheck:
            test: ["CMD", "curl", "-f", "http://127.0.0.1:5000/status"]
            interval: 60s
            timeout: 10s
            retries: 5

    opengsync-celery-worker:
        image: ghcr.io/lutrarutra/opengsync-app/worker:${APP_VERSION:-latest}
        platform: linux/amd64
        user: "${PUID:-1000}:${PGID:-1000}"
        container_name: opengsync-celery-worker
        restart: unless-stopped
        environment:
            TZ: ${TIMEZONE}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_HOST: ${POSTGRES_HOST}
            POSTGRES_PORT: ${POSTGRES_PORT}
        volumes:
            - ${OPENGSYNC_CONFIG_FILE}:/app/opengsync.yaml:ro
            - ${ILLUMINA_RUN_FOLDER}:/illumina_run_folder:ro
            - ${LOG_DIR}/celery-worker:/logs
            - ${UPLOADS_DIR}:/uploads
        depends_on:
            opengsync-celery-beat:
                condition: service_started
                restart: true
            postgres:
                condition: service_healthy
                restart: true
            redis-cache:
                condition: service_healthy
                restart: true

    opengsync-celery-beat:
        image: ghcr.io/lutrarutra/opengsync-app/worker:${APP_VERSION:-latest}
        platform: linux/amd64
        user: "${PUID:-1000}:${PGID:-1000}"
        container_name: opengsync-celery-beat
        restart: unless-stopped
        environment:
            TZ: ${TIMEZONE}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_HOST: ${POSTGRES_HOST}
            POSTGRES_PORT: ${POSTGRES_PORT}
        volumes:
            - ${OPENGSYNC_CONFIG_FILE}:/app/opengsync.yaml:ro
            - ${LOG_DIR}/celery-beat:/logs
        depends_on:
            postgres:
                condition: service_healthy
                restart: true
            redis-cache:
                condition: service_healthy
                restart: true
        command: >
            celery -A opengsync_worker.celery beat --loglevel=info

    tailwind-compiler:
        platform: linux/amd64
        container_name: tailwind-compiler
        tty: true
        restart: "no"
        build:
          context: .
          dockerfile: ./services/tailwind-compiler/Dockerfile
        volumes:
            - compiled_css:/app/static/style/compiled
        environment:
            - TZ=${TIMEZONE}
        command: "tailwindcss -i /app/style/style.css -o /app/static/style/compiled/style.css --minify"

    nginx:
        image: ghcr.io/lutrarutra/opengsync-app/nginx:${APP_VERSION:-latest}
        platform: linux/amd64
        container_name: nginx-proxy
        restart: unless-stopped
        ports:
            - 80:80
            - 443:443
        volumes:
            - compiled_css:/static/style/compiled:ro
            - ${MEDIA_DIR}:/media:ro
            - ${UPLOADS_DIR}:/uploads:ro
            - ${NGINX_CONFIG_DIR}:/etc/nginx/conf.d:ro
        depends_on:
            opengsync-app:
                condition: service_started
                restart: true
            tailwind-compiler:
                condition: service_completed_successfully
        environment:
            TZ: ${TIMEZONE}
        command: /bin/bash -c "nginx -g 'daemon off;'"

    redis-cache:
        platform: linux/amd64
        container_name: redis-cache
        image: redis:8.0.3-alpine3.21
        restart: unless-stopped
        volumes:
            - redis_data:/data
        environment:
            TZ: ${TIMEZONE}
        healthcheck:
            test: ["CMD", "redis-cli", "-p", "6379", "ping"]
            interval: 10s
            timeout: 10s
            retries: 5
        command: --port 6379 --maxmemory 2048mb --maxmemory-policy volatile-lru --save 900 1 --save 300 10 --save 60 1000

    postgres:
        image: ghcr.io/lutrarutra/opengsync-app/postgres:${APP_VERSION:-latest}
        platform: linux/amd64
        container_name: postgres
        restart: unless-stopped
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
            PGPORT: ${POSTGRES_PORT}
            TZ: ${TIMEZONE}
            # pgBackRest SCP repository
            PGBACKREST_REPO1_TYPE: scp
            PGBACKREST_REPO1_HOST: ${PGBACKREST_REPO1_HOST}
            PGBACKREST_REPO1_USER: ${PGBACKREST_REPO1_USER}
            PGBACKREST_REPO1_PATH: ${PGBACKREST_REPO1_PATH}
            PGBACKREST_REPO1_SSH_KEY: /etc/pgbackrest/id_ed25519
        expose:
            - ${POSTGRES_PORT}
        ports:
            - ${POSTGRES_PORT}:${POSTGRES_PORT}
        volumes:
            - ./services/db/postgresql.prod.conf:/etc/postgresql.conf:ro
            - ./services/db/pgbackrest.conf:/etc/pgbackrest/pgbackrest.conf:ro
            - postgres_data:/var/lib/postgresql/data
            - ${PGBACKREST_SSH_KEY}:/etc/pgbackrest/id_ed25519:ro
            - ${PGBACKREST_KNOWN_HOSTS}:/etc/ssh/ssh_known_hosts:ro
        healthcheck:
            test: ["CMD", "pg_isready", "-d", "${POSTGRES_DB}", "-U", "${POSTGRES_USER}"]
            interval: 10s
            timeout: 10s
            retries: 5
        command: "postgres -c config_file=/etc/postgresql.conf"

    pgadmin:
        platform: linux/amd64
        container_name: pgadmin
        image: dpage/pgadmin4:latest
        environment:
            PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
            PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
            TZ: ${TIMEZONE}
        ports:
            - ${PGADMIN_PORT}:80
        restart: unless-stopped
        volumes:
            - pgadmin_data:/var/lib/pgadmin
        depends_on:
            postgres:
                condition: service_healthy
                restart: true
        attach: false  # no logs

volumes:
    compiled_css:
    pgadmin_data:
    redis_data:
    postgres_data:
        external: true
        name: opengsync-prod_postgres_data