"""empty message

Revision ID: 0b83d9ce2313
Revises: 210e661bf248
Create Date: 2025-12-30 16:24:35.103784

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b83d9ce2313'
down_revision: Union[str, Sequence[str], None] = '210e661bf248'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('design_pool_flow_cell_link', sa.Column('lane_num', sa.SmallInteger(), nullable=False))
    op.drop_column('design_pool_flow_cell_link', 'lane')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('design_pool_flow_cell_link', sa.Column('lane', sa.SMALLINT(), autoincrement=False, nullable=False))
    op.drop_column('design_pool_flow_cell_link', 'lane_num')
    # ### end Alembic commands ###
