"""empty message

Revision ID: 210e661bf248
Revises: 37ef9eb70e85
Create Date: 2025-12-30 16:04:13.838988

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '210e661bf248'
down_revision: Union[str, Sequence[str], None] = '37ef9eb70e85'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flow_cell_design',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=16), nullable=False),
    sa.Column('workflow_id', sa.SmallInteger(), nullable=False),
    sa.Column('cycles_r1', sa.SmallInteger(), nullable=False),
    sa.Column('cycles_r2', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_flow_cell_design_name'), 'flow_cell_design', ['name'], unique=False)
    op.create_index('trgm_fc_design_name_idx', 'flow_cell_design', [sa.literal_column('lower(name) gin_trgm_ops')], unique=False, postgresql_using='gin')
    op.create_table('pool_design',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('pool_id', sa.Integer(), nullable=True),
    sa.Column('num_m_requested_reads', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['pool_id'], ['pool.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pool_design_name'), 'pool_design', ['name'], unique=False)
    op.create_index('trgm_pool_design_name_idx', 'pool_design', [sa.literal_column('lower(name) gin_trgm_ops')], unique=False, postgresql_using='gin')
    op.create_table('design_pool_flow_cell_link',
    sa.Column('pool_design_id', sa.Integer(), nullable=False),
    sa.Column('flow_cell_design_id', sa.Integer(), nullable=False),
    sa.Column('lane', sa.SmallInteger(), nullable=False),
    sa.Column('num_m_reads', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['flow_cell_design_id'], ['flow_cell_design.id'], ),
    sa.ForeignKeyConstraint(['pool_design_id'], ['pool_design.id'], ),
    sa.PrimaryKeyConstraint('pool_design_id', 'flow_cell_design_id', 'lane')
    )
    op.drop_constraint(op.f('library_protocol_id_fkey'), 'library', type_='foreignkey')
    op.create_foreign_key(None, 'library', 'protocol', ['protocol_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'library', type_='foreignkey')
    op.create_foreign_key(op.f('library_protocol_id_fkey'), 'library', 'protocol', ['protocol_id'], ['id'])
    op.drop_table('design_pool_flow_cell_link')
    op.drop_index('trgm_pool_design_name_idx', table_name='pool_design', postgresql_using='gin')
    op.drop_index(op.f('ix_pool_design_name'), table_name='pool_design')
    op.drop_table('pool_design')
    op.drop_index('trgm_fc_design_name_idx', table_name='flow_cell_design', postgresql_using='gin')
    op.drop_index(op.f('ix_flow_cell_design_name'), table_name='flow_cell_design')
    op.drop_table('flow_cell_design')
    # ### end Alembic commands ###
