"""added review checklist

Revision ID: 22bce3e03dd9
Revises: 93dd485dd7c4
Create Date: 2026-05-06 13:14:21.077653

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '22bce3e03dd9'
down_revision: Union[str, Sequence[str], None] = '93dd485dd7c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('seq_request', sa.Column('review_checklist', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('seq_request', 'review_checklist')
    # ### end Alembic commands ###
