"""project and seq_request assignees link

Revision ID: 37ef9eb70e85
Revises: b2f4986a8da3
Create Date: 2025-11-27 10:59:02.529442

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37ef9eb70e85'
down_revision: Union[str, Sequence[str], None] = 'b2f4986a8da3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_assignee_link',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['lims_user.id'], ),
    sa.PrimaryKeyConstraint('project_id', 'user_id')
    )
    op.create_table('seq_request_assignee_link',
    sa.Column('seq_request_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['seq_request_id'], ['seq_request.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['lims_user.id'], ),
    sa.PrimaryKeyConstraint('seq_request_id', 'user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('seq_request_assignee_link')
    op.drop_table('project_assignee_link')
    # ### end Alembic commands ###
