"""empty message

Revision ID: 4b00d9482da6
Revises: f7e57fc6ccaa
Create Date: 2025-09-08 09:21:43.157468

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b00d9482da6'
down_revision: Union[str, Sequence[str], None] = 'f7e57fc6ccaa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('pool_dilution_pool_id_fkey'), 'pool_dilution', type_='foreignkey')
    op.create_foreign_key(None, 'pool_dilution', 'pool', ['pool_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pool_dilution', type_='foreignkey')
    op.create_foreign_key(op.f('pool_dilution_pool_id_fkey'), 'pool_dilution', 'pool', ['pool_id'], ['id'])
    # ### end Alembic commands ###
