"""added library qc column

Revision ID: 784f986f615d
Revises: 22bce3e03dd9
Create Date: 2026-05-21 09:56:36.866797

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '784f986f615d'
down_revision: Union[str, Sequence[str], None] = '22bce3e03dd9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('library', sa.Column('qc', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('library', 'qc')
    # ### end Alembic commands ###
