"""SeqQuality restructuring

Revision ID: 7cce32d72fdd
Revises: f38de7ef5537
Create Date: 2025-11-18 10:46:37.806732

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7cce32d72fdd'
down_revision: Union[str, Sequence[str], None] = 'f38de7ef5537'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('seq_quality',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lane', sa.Integer(), nullable=False),
    sa.Column('num_reads', sa.BigInteger(), nullable=False),
    sa.Column('qc', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('library_id', sa.Integer(), nullable=True),
    sa.Column('experiment_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiment.id'], ),
    sa.ForeignKeyConstraint(['library_id'], ['library.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('seqquality')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('seqquality',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('lane', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('num_lane_reads', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('num_library_reads', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('mean_quality_pf_r1', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('q30_perc_r1', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('mean_quality_pf_r2', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('q30_perc_r2', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('mean_quality_pf_i1', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('q30_perc_i1', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('mean_quality_pf_i2', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('q30_perc_i2', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('library_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('experiment_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiment.id'], name=op.f('seqquality_experiment_id_fkey')),
    sa.ForeignKeyConstraint(['library_id'], ['library.id'], name=op.f('seqquality_library_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('seqquality_pkey'))
    )
    op.drop_table('seq_quality')
    # ### end Alembic commands ###
