"""empty message

Revision ID: a191a58bfb18
Revises: 
Create Date: 2025-08-14 09:39:21.861241

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a191a58bfb18'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feature', sa.Column('identifier', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_feature_identifier'), 'feature', ['identifier'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_feature_identifier'), table_name='feature')
    op.drop_column('feature', 'identifier')
    # ### end Alembic commands ###
