"""empty message

Revision ID: a747860f8fdb
Revises: 530fb3e2c98d
Create Date: 2025-09-11 08:33:48.599126

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a747860f8fdb'
down_revision: Union[str, Sequence[str], None] = '530fb3e2c98d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('data_path', 'path',
               existing_type=sa.VARCHAR(length=1024),
               type_=sa.String(length=2048),
               existing_nullable=False)
    op.create_index(op.f('ix_data_path_path'), 'data_path', ['path'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_data_path_path'), table_name='data_path')
    op.alter_column('data_path', 'path',
               existing_type=sa.String(length=2048),
               type_=sa.VARCHAR(length=1024),
               existing_nullable=False)
    # ### end Alembic commands ###
