"""LabProtocol rename to LabChecklistType

Revision ID: b0d7d8d56d33
Revises: 530338456ef5
Create Date: 2025-11-19 10:25:24.171420

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0d7d8d56d33'
down_revision: Union[str, Sequence[str], None] = '530338456ef5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('lab_prep', 'checklist_type_id',
               existing_type=sa.SMALLINT(),
               nullable=False)
    op.drop_column('lab_prep', 'protocol_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lab_prep', sa.Column('protocol_id', sa.SMALLINT(), autoincrement=False, nullable=False))
    op.alter_column('lab_prep', 'checklist_type_id',
               existing_type=sa.SMALLINT(),
               nullable=True)
    # ### end Alembic commands ###
