"""merged pool

Revision ID: b2f4986a8da3
Revises: b0d7d8d56d33
Create Date: 2025-11-25 11:58:03.938141

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2f4986a8da3'
down_revision: Union[str, Sequence[str], None] = 'b0d7d8d56d33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pool', sa.Column('merged_to_pool_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'pool', 'pool', ['merged_to_pool_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pool', type_='foreignkey')
    op.drop_column('pool', 'merged_to_pool_id')
    # ### end Alembic commands ###
