"""made number of cycles optional in experiment

Revision ID: cb81566d3066
Revises: 050c8975bede
Create Date: 2026-03-20 10:05:53.481754

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb81566d3066'
down_revision: Union[str, Sequence[str], None] = '050c8975bede'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('experiment', 'r1_cycles',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('experiment', 'i1_cycles',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('experiment', 'i1_cycles',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('experiment', 'r1_cycles',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
