"""added library-sample qc column

Revision ID: db7f9caeaeef
Revises: 784f986f615d
Create Date: 2026-05-21 13:53:15.454891

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'db7f9caeaeef'
down_revision: Union[str, Sequence[str], None] = '784f986f615d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sample_library_link', sa.Column('qc', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sample_library_link', 'qc')
    # ### end Alembic commands ###
