"""empty message

Revision ID: f7e57fc6ccaa
Revises: 67c88695c43c
Create Date: 2025-09-04 10:10:15.100934

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7e57fc6ccaa'
down_revision: Union[str, Sequence[str], None] = '67c88695c43c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('share_token_uuid', sa.CHAR(length=36), nullable=True))
    op.create_foreign_key(None, 'project', 'share_token', ['share_token_uuid'], ['uuid'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'project', type_='foreignkey')
    op.drop_column('project', 'share_token_uuid')
    # ### end Alembic commands ###
