"""empty message

Revision ID: fd486cb8a2b4
Revises: e55c814fd42e
Create Date: 2025-11-13 10:00:56.145899

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd486cb8a2b4'
down_revision: Union[str, Sequence[str], None] = 'e55c814fd42e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('protocol',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('read_structure', sa.String(length=256), nullable=True),
    sa.Column('assay_type_id', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_protocol_name'), 'protocol', ['name'], unique=True)
    op.create_index('trgm_protocol_name_idx', 'protocol', [sa.literal_column('lower(name) gin_trgm_ops')], unique=False, postgresql_using='gin')
    op.create_table('protocol_kit_link',
    sa.Column('protocol_id', sa.Integer(), nullable=False),
    sa.Column('kit_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['kit_id'], ['kit.id'], ),
    sa.ForeignKeyConstraint(['protocol_id'], ['protocol.id'], ),
    sa.PrimaryKeyConstraint('protocol_id', 'kit_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('protocol_kit_link')
    op.drop_index('trgm_protocol_name_idx', table_name='protocol', postgresql_using='gin')
    op.drop_index(op.f('ix_protocol_name'), table_name='protocol')
    op.drop_table('protocol')
    # ### end Alembic commands ###
