"""AssayType renamed to ServiceType

Revision ID: 530338456ef5
Revises: 7cce32d72fdd
Create Date: 2025-11-19 10:10:02.571666

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '530338456ef5'
down_revision: Union[str, Sequence[str], None] = '7cce32d72fdd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('lab_prep', 'service_type_id',
               existing_type=sa.SMALLINT(),
               nullable=False)
    op.drop_column('lab_prep', 'assay_type_id')
    op.alter_column('library', 'service_type_id',
               existing_type=sa.SMALLINT(),
               nullable=False)
    op.drop_column('library', 'assay_type_id')
    op.alter_column('protocol', 'service_type_id',
               existing_type=sa.SMALLINT(),
               nullable=False)
    op.drop_column('protocol', 'assay_type_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('protocol', sa.Column('assay_type_id', sa.SMALLINT(), autoincrement=False, nullable=False))
    op.alter_column('protocol', 'service_type_id',
               existing_type=sa.SMALLINT(),
               nullable=True)
    op.add_column('library', sa.Column('assay_type_id', sa.SMALLINT(), autoincrement=False, nullable=False))
    op.alter_column('library', 'service_type_id',
               existing_type=sa.SMALLINT(),
               nullable=True)
    op.add_column('lab_prep', sa.Column('assay_type_id', sa.SMALLINT(), autoincrement=False, nullable=False))
    op.alter_column('lab_prep', 'service_type_id',
               existing_type=sa.SMALLINT(),
               nullable=True)
    # ### end Alembic commands ###
