"""empty message

Revision ID: 530fb3e2c98d
Revises: 5e70ce49276e
Create Date: 2025-09-10 13:06:49.534467

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '530fb3e2c98d'
down_revision: Union[str, Sequence[str], None] = '5e70ce49276e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('seq_run', sa.Column('timestamps', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('seq_run', 'timestamps')
    # ### end Alembic commands ###
