"""empty message

Revision ID: 5e70ce49276e
Revises: 4b00d9482da6
Create Date: 2025-09-10 10:32:32.641482

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e70ce49276e'
down_revision: Union[str, Sequence[str], None] = '4b00d9482da6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('contact', 'address',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=1024),
               existing_nullable=True)
    op.alter_column('seq_request', 'billing_code',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.String(length=256),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('seq_request', 'billing_code',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=32),
               existing_nullable=True)
    op.alter_column('contact', 'address',
               existing_type=sa.String(length=1024),
               type_=sa.VARCHAR(length=128),
               existing_nullable=True)
    # ### end Alembic commands ###
