"""empty message

Revision ID: 6036c335a610
Revises: a191a58bfb18
Create Date: 2025-08-22 11:20:05.187733

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6036c335a610'
down_revision: Union[str, Sequence[str], None] = 'a191a58bfb18'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_project_identifier'), table_name='project')
    op.create_index(op.f('ix_project_identifier'), 'project', ['identifier'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_project_identifier'), table_name='project')
    op.create_index(op.f('ix_project_identifier'), 'project', ['identifier'], unique=True)
    # ### end Alembic commands ###
