"""added merge ratios to pool table

Revision ID: 93dd485dd7c4
Revises: ff46c018cb75
Create Date: 2026-05-04 09:02:36.015269

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '93dd485dd7c4'
down_revision: Union[str, Sequence[str], None] = 'ff46c018cb75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pool', sa.Column('merge_ratios', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pool', 'merge_ratios')
    # ### end Alembic commands ###
