"""add protocol_id to library

Revision ID: c7165f1f03e4
Revises: 418712f21d04
Create Date: 2025-11-14 14:36:03.449796

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7165f1f03e4'
down_revision: Union[str, Sequence[str], None] = '418712f21d04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('library', sa.Column('protocol_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'library', 'protocol', ['protocol_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'library', type_='foreignkey')
    op.drop_column('library', 'protocol_id')
    # ### end Alembic commands ###
