"""empty message

Revision ID: e55c814fd42e
Revises: a747860f8fdb
Create Date: 2025-10-15 10:29:33.937239

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e55c814fd42e'
down_revision: Union[str, Sequence[str], None] = 'a747860f8fdb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('library_index', sa.Column('orientation', sa.SmallInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('library_index', 'orientation')
    # ### end Alembic commands ###
