FROM python:3.13-slim

WORKDIR /app

RUN apt update
RUN apt install build-essential libpq-dev curl postgresql-client -y

RUN pip install --upgrade pip
COPY . /app/

RUN pip install -e /app/opengsync-db
RUN pip install -e /app/opengsync-server
RUN chmod +x /app/entrypoint.sh