FROM python:3.13-slim

WORKDIR /usr/src/app

RUN apt update
RUN apt install build-essential libpq-dev curl postgresql-client -y

RUN pip install --upgrade pip
COPY . /usr/src/app/

RUN pip install -e /usr/src/app/opengsync-db
RUN pip install -e /usr/src/app/opengsync-server
RUN chmod +x /usr/src/app/entrypoint.sh